### ISSUE TITLE
Broken Launcher

### ISSUE THREAD

**Issue by patham9** [automenta/narchy#4]
When running Launcher.java in the nars package (skynet5 branch):

java.io.IOException: File <Hack-Regular.ttf> doesn't exist.
	at jogamp.graph.font.typecast.ot.OTFontCollection.read(OTFontCollection.java:121)
	at jogamp.graph.font.typecast.ot.OTFontCollection.create(OTFontCollection.java:64)
	at jogamp.graph.font.typecast.TypecastFontConstructor.create(TypecastFontConstructor.java:43)
	at spacegraph.space2d.widget.text.LabelRenderer$2.<init>(LabelRenderer.java:103)
	at spacegraph.space2d.widget.text.LabelRenderer.<clinit>(LabelRenderer.java:62)
	at spacegraph.space2d.widget.text.VectorLabel.<init>(VectorLabel.java:23)
	at spacegraph.space2d.widget.meta.MetaFrame.<init>(MetaFrame.java:24)
	at spacegraph.space2d.widget.meta.ObjectSurface$ObjectMetaFrame.<init>(ObjectSurface.java:205)
	at spacegraph.space2d.widget.meta.ObjectSurface.collectElements(ObjectSurface.java:197)
	at spacegraph.space2d.widget.meta.ObjectSurface.collect(ObjectSurface.java:129)
	at spacegraph.space2d.widget.meta.ObjectSurface.collect(ObjectSurface.java:79)
	at spacegraph.space2d.widget.meta.ObjectSurface.start(ObjectSurface.java:70)
	at spacegraph.space2d.container.AbstractMutableContainer.lambda$start$0(AbstractMutableContainer.java:17)
	at spacegraph.space2d.container.MutableContainer.lambda$forEach$e71cd6a9$1(MutableContainer.java:185)
	at org.eclipse.collections.impl.list.mutable.FastList.each(FastList.java:587)
	at org.eclipse.collections.impl.AbstractRichIterable.forEach(AbstractRichIterable.java:567)
	at spacegraph.space2d.container.MutableContainer.forEach(MutableContainer.java:185)
	at spacegraph.space2d.container.AbstractMutableContainer.start(AbstractMutableContainer.java:12)
	at spacegraph.space2d.container.MutableContainer._add(MutableContainer.java:114)
	at spacegraph.space2d.container.MutableContainer.add(MutableContainer.java:104)
	at spacegraph.space2d.hud.ZoomOrtho.start(ZoomOrtho.java:98)
	at spacegraph.video.JoglSpace.lambda$add$1(JoglSpace.java:78)
	at spacegraph.video.JoglSpace.lambda$flush$4(JoglSpace.java:143)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.bulkRemove(ConcurrentLinkedQueue.java:1004)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.removeIf(ConcurrentLinkedQueue.java:964)
	at spacegraph.video.JoglSpace.flush(JoglSpace.java:142)
	at spacegraph.video.JoglSpace.init(JoglSpace.java:137)
	at spacegraph.video.JoglWindow.init(JoglWindow.java:381)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
	at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:119)
	at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:141)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4383)
	at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:4317)
	at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1306)
	at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1318)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:145)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)

**Comment by automenta** [comment]
i chose a nice font to include with the project
https://www.fontsquirrel.com/fonts/courier-prime-code
